# Generated by Django 3.1.3 on 2021-03-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupport',
            fields=[
                ('user_id', models.IntegerField(max_length=120)),
                ('message', models.CharField(max_length=120)),
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
