# Generated by Django 3.1.3 on 2021-03-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customersupport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
