# Generated by Django 3.1.3 on 2021-03-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210323_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupport',
            name='status',
            field=models.CharField(default='Request', max_length=120),
        ),
    ]
